# Generated by Django 4.2.4 on 2023-09-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
