# Generated by Django 4.2.4 on 2023-09-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='content',
        ),
    ]
